import { Property, PropertyType, PropertyStatus, ApprovalStatus } from '@/types/property'

export const mockProperties: Property[] = [
  {
    id: '1',
    slug: 'casa-luxo-jardins-sao-paulo',
    title: 'Casa de Luxo no Jardins',
    description:
      'Magnífica casa de alto padrão localizada no bairro mais nobre de São Paulo. Com acabamentos importados, piscina aquecida, academia, home theater e jardim paisagístico. Ideal para famílias que buscam conforto e sofisticação em uma das melhores localizações da cidade.',
    type: PropertyType.CASA,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 2500000,
    condominioPrice: 0,
    iptuPrice: 18000,
    area: 420,
    bedrooms: 5,
    bathrooms: 6,
    parkingSpots: 4,
    city: 'São Paulo',
    neighborhood: 'Jardins',
    address: 'Rua Oscar Freire, 1200',
    state: 'SP',
    zipCode: '01426-001',
    images: [
      {
        id: '1-1',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        alt: 'Fachada da casa',
        isPrimary: true,
      },
      {
        id: '1-2',
        url: 'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=800&q=80',
        alt: 'Sala de estar',
      },
      {
        id: '1-3',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
        alt: 'Piscina',
      },
      {
        id: '1-4',
        url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
        alt: 'Cozinha',
      },
    ],
    featured: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    brokerName: 'Carlos Mendes',
    brokerId: 'broker-1',
  },
  {
    id: '2',
    slug: 'apartamento-moderno-pinheiros',
    title: 'Apartamento Moderno em Pinheiros',
    description:
      'Apartamento contemporâneo com vista para o parque, localizado em Pinheiros, um dos bairros mais vibrantes de São Paulo. Com arquitetura moderna, varanda gourmet e lazer completo no condomínio. A poucos metros do metrô e das principais avenidas.',
    type: PropertyType.APARTAMENTO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 980000,
    condominioPrice: 1200,
    iptuPrice: 4800,
    area: 128,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    city: 'São Paulo',
    neighborhood: 'Pinheiros',
    address: 'Rua dos Pinheiros, 850, Apto 72',
    state: 'SP',
    zipCode: '05422-001',
    images: [
      {
        id: '2-1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        alt: 'Sala de estar',
        isPrimary: true,
      },
      {
        id: '2-2',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        alt: 'Quarto principal',
      },
      {
        id: '2-3',
        url: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80',
        alt: 'Cozinha americana',
      },
    ],
    featured: true,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    brokerName: 'Ana Lima',
    brokerId: 'broker-2',
  },
  {
    id: '3',
    slug: 'terreno-campinas-alphaville',
    title: 'Terreno em Condomínio Alphaville Campinas',
    description:
      'Excelente terreno em condomínio fechado de alto padrão em Campinas. Topografia plana, ideal para construção de residência de luxo. Segurança 24 horas, área verde preservada e infraestrutura completa. Oportunidade única de investimento.',
    type: PropertyType.TERRENO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 450000,
    condominioPrice: 850,
    iptuPrice: 2400,
    area: 600,
    bedrooms: 0,
    bathrooms: 0,
    parkingSpots: 0,
    city: 'Campinas',
    neighborhood: 'Alphaville',
    address: 'Rua das Palmeiras, Lote 42',
    state: 'SP',
    zipCode: '13098-324',
    images: [
      {
        id: '3-1',
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        alt: 'Vista do terreno',
        isPrimary: true,
      },
      {
        id: '3-2',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        alt: 'Área verde',
      },
    ],
    featured: false,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
    brokerName: 'Pedro Costa',
    brokerId: 'broker-3',
  },
  {
    id: '4',
    slug: 'apartamento-aluguel-moema',
    title: 'Apartamento para Alugar em Moema',
    description:
      'Apartamento completamente mobiliado e decorado no coração de Moema. Varanda com churrasqueira, condomínio com piscina, academia e salão de festas. A dois quarteirões do Parque Ibirapuera, em localização privilegiada.',
    type: PropertyType.APARTAMENTO,
    status: PropertyStatus.ALUGUEL,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 6500,
    condominioPrice: 950,
    iptuPrice: 400,
    area: 95,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    city: 'São Paulo',
    neighborhood: 'Moema',
    address: 'Alameda dos Arapanés, 302, Apto 51',
    state: 'SP',
    zipCode: '04524-001',
    images: [
      {
        id: '4-1',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
        alt: 'Sala integrada',
        isPrimary: true,
      },
      {
        id: '4-2',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        alt: 'Quarto',
      },
    ],
    featured: true,
    createdAt: '2024-02-05T10:00:00Z',
    updatedAt: '2024-02-05T10:00:00Z',
    brokerName: 'Ana Lima',
    brokerId: 'broker-2',
  },
  {
    id: '5',
    slug: 'sala-comercial-santos-centro',
    title: 'Sala Comercial no Centro de Santos',
    description:
      'Sala comercial de alto padrão no centro empresarial de Santos. Ideal para escritórios, consultórios ou sedes corporativas. Com recepção, copa, área de reuniões e estacionamento. Localização estratégica próxima ao porto e ao centro histórico.',
    type: PropertyType.COMERCIAL,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 680000,
    condominioPrice: 1800,
    iptuPrice: 6000,
    area: 180,
    bedrooms: 0,
    bathrooms: 3,
    parkingSpots: 5,
    city: 'Santos',
    neighborhood: 'Centro',
    address: 'Avenida Ana Costa, 500, Conjunto 1201',
    state: 'SP',
    zipCode: '11060-002',
    images: [
      {
        id: '5-1',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
        alt: 'Espaço comercial',
        isPrimary: true,
      },
      {
        id: '5-2',
        url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
        alt: 'Sala de reunião',
      },
    ],
    featured: false,
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-10T10:00:00Z',
    brokerName: 'Carlos Mendes',
    brokerId: 'broker-1',
  },
  {
    id: '6',
    slug: 'casa-condominio-campinas-barao-geraldo',
    title: 'Casa em Condomínio Barão Geraldo',
    description:
      'Belíssima casa em condomínio fechado na região de Barão Geraldo, Campinas. Projeto arquitetônico moderno com amplos espaços sociais, cozinha gourmet, suíte master com closet e banheiro com banheira. Jardim e quintal privativos.',
    type: PropertyType.CASA,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 1250000,
    condominioPrice: 1500,
    iptuPrice: 8400,
    area: 320,
    bedrooms: 4,
    bathrooms: 4,
    parkingSpots: 3,
    city: 'Campinas',
    neighborhood: 'Barão Geraldo',
    address: 'Rua das Acácias, 78',
    state: 'SP',
    zipCode: '13085-100',
    images: [
      {
        id: '6-1',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
        alt: 'Fachada da casa',
        isPrimary: true,
      },
      {
        id: '6-2',
        url: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
        alt: 'Sala de estar',
      },
      {
        id: '6-3',
        url: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800&q=80',
        alt: 'Cozinha',
      },
    ],
    featured: false,
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
    brokerName: 'Pedro Costa',
    brokerId: 'broker-3',
  },
  {
    id: '7',
    slug: 'apartamento-aluguel-santos-beira-mar',
    title: 'Apartamento Beira-Mar em Santos',
    description:
      'Apartamento com vista privilegiada para o mar em Santos. Totalmente reformado, com acabamentos modernos, varanda frente ao mar, condomínio com piscina e espaço gourmet. Perfeito para quem busca qualidade de vida com a brisa do mar.',
    type: PropertyType.APARTAMENTO,
    status: PropertyStatus.ALUGUEL,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 5800,
    condominioPrice: 1100,
    iptuPrice: 350,
    area: 110,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    city: 'Santos',
    neighborhood: 'Gonzaga',
    address: 'Avenida Presidente Wilson, 1800, Apto 801',
    state: 'SP',
    zipCode: '11065-202',
    images: [
      {
        id: '7-1',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        alt: 'Vista para o mar',
        isPrimary: true,
      },
      {
        id: '7-2',
        url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
        alt: 'Sala com vista',
      },
    ],
    featured: false,
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
    brokerName: 'Ana Lima',
    brokerId: 'broker-2',
  },
  {
    id: '8',
    slug: 'terreno-sao-paulo-granja-viana',
    title: 'Terreno em Granja Viana',
    description:
      'Terreno de alto padrão na região de Granja Viana, com área de mata nativa preservada. Localização privilegiada próxima a colégios particulares, shoppings e vias de acesso rápido a São Paulo. Topografia levemente inclinada, ideal para projeto com cave.',
    type: PropertyType.TERRENO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 380000,
    condominioPrice: 600,
    iptuPrice: 1800,
    area: 500,
    bedrooms: 0,
    bathrooms: 0,
    parkingSpots: 0,
    city: 'São Paulo',
    neighborhood: 'Granja Viana',
    address: 'Estrada do Embu, Lote 15',
    state: 'SP',
    zipCode: '06710-000',
    images: [
      {
        id: '8-1',
        url: 'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80',
        alt: 'Vista do terreno',
        isPrimary: true,
      },
    ],
    featured: false,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    brokerName: 'Carlos Mendes',
    brokerId: 'broker-1',
  },
  {
    id: '9',
    slug: 'galpao-comercial-campinas-polo-industrial',
    title: 'Galpão Comercial no Polo Industrial de Campinas',
    description:
      'Galpão industrial moderno com pé-direito alto, piso epóxi, docas para carga e descarga, refeitório, vestiários e escritório administrativo. Localizado no polo industrial de Campinas, com fácil acesso à Rodovia Anhanguera e à SP-65. Ideal para logística e indústria.',
    type: PropertyType.COMERCIAL,
    status: PropertyStatus.ALUGUEL,
    approvalStatus: ApprovalStatus.APROVADO,
    price: 12000,
    condominioPrice: 2200,
    iptuPrice: 900,
    area: 800,
    bedrooms: 0,
    bathrooms: 6,
    parkingSpots: 15,
    city: 'Campinas',
    neighborhood: 'Polo Industrial',
    address: 'Rua Industrial, 500',
    state: 'SP',
    zipCode: '13054-750',
    images: [
      {
        id: '9-1',
        url: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&q=80',
        alt: 'Galpão industrial',
        isPrimary: true,
      },
      {
        id: '9-2',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
        alt: 'Interior do galpão',
      },
    ],
    featured: false,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
    brokerName: 'Pedro Costa',
    brokerId: 'broker-3',
  },
]

export const pendingProperties: Property[] = [
  {
    id: 'p1',
    slug: 'cobertura-vila-madalena-pendente',
    title: 'Cobertura Duplex em Vila Madalena',
    description:
      'Cobertura duplex com terraço privativo de 80m², churrasqueira, jacuzzi e vista 360° para a cidade. Acabamentos de alto padrão, cozinha gourmet integrada à sala de jantar. Localização única no coração de Vila Madalena, próxima às melhores opções de gastronomia e cultura.',
    type: PropertyType.APARTAMENTO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.PENDENTE,
    price: 1800000,
    condominioPrice: 2200,
    iptuPrice: 12000,
    area: 210,
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 3,
    city: 'São Paulo',
    neighborhood: 'Vila Madalena',
    address: 'Rua Harmonia, 450, Cobertura',
    state: 'SP',
    zipCode: '05435-000',
    images: [
      {
        id: 'p1-1',
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
        alt: 'Terraço da cobertura',
        isPrimary: true,
      },
      {
        id: 'p1-2',
        url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
        alt: 'Sala de estar',
      },
    ],
    featured: false,
    createdAt: '2024-05-01T14:30:00Z',
    updatedAt: '2024-05-01T14:30:00Z',
    brokerId: 'broker-2',
    brokerName: 'Ana Lima',
    brokerPhone: '(11) 98888-1111',
  },
  {
    id: 'p2',
    slug: 'casa-alphaville-pendente',
    title: 'Casa Alto Padrão em Alphaville',
    description:
      'Espetacular residência em condomínio fechado Alphaville com infraestrutura completa. Piscina aquecida, sauna, espaço gourmet, home cinema e paisagismo premiado. Segurança 24h, clube com quadras esportivas e área verde.',
    type: PropertyType.CASA,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.PENDENTE,
    price: 3200000,
    condominioPrice: 3500,
    iptuPrice: 22000,
    area: 580,
    bedrooms: 6,
    bathrooms: 7,
    parkingSpots: 5,
    city: 'Barueri',
    neighborhood: 'Alphaville',
    address: 'Alameda Araguaia, 2200',
    state: 'SP',
    zipCode: '06455-000',
    images: [
      {
        id: 'p2-1',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
        alt: 'Fachada da mansão',
        isPrimary: true,
      },
      {
        id: 'p2-2',
        url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80',
        alt: 'Piscina',
      },
    ],
    featured: false,
    createdAt: '2024-05-02T09:15:00Z',
    updatedAt: '2024-05-02T09:15:00Z',
    brokerId: 'broker-1',
    brokerName: 'Carlos Mendes',
    brokerPhone: '(11) 97777-2222',
  },
  {
    id: 'p3',
    slug: 'apartamento-higienopolis-pendente',
    title: 'Apartamento Reformado em Higienópolis',
    description:
      'Apartamento completamente reformado no tradicional bairro de Higienópolis. Piso de mármore, cozinha planejada, banheiro com revestimento italiano, ar-condicionado central. Prédio histórico com portaria 24h, a 5 minutos do metrô.',
    type: PropertyType.APARTAMENTO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.PENDENTE,
    price: 750000,
    condominioPrice: 1800,
    iptuPrice: 5200,
    area: 145,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    city: 'São Paulo',
    neighborhood: 'Higienópolis',
    address: 'Avenida Higienópolis, 890, Apto 122',
    state: 'SP',
    zipCode: '01238-001',
    images: [
      {
        id: 'p3-1',
        url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
        alt: 'Sala principal',
        isPrimary: true,
      },
    ],
    featured: false,
    createdAt: '2024-05-03T16:45:00Z',
    updatedAt: '2024-05-03T16:45:00Z',
    brokerId: 'broker-4',
    brokerName: 'Fernanda Rocha',
    brokerPhone: '(11) 96666-3333',
  },
  {
    id: 'p4',
    slug: 'terreno-cotia-pendente',
    title: 'Terreno com Mata Nativa em Cotia',
    description:
      'Terreno privilegiado em Cotia com área de mata nativa preservada, nascente d\'água e vista para a Serra da Cantareira. Ideal para projeto de casa sustentável ou sítio de lazer. Documentação em dia, escritura registrada.',
    type: PropertyType.TERRENO,
    status: PropertyStatus.VENDA,
    approvalStatus: ApprovalStatus.PENDENTE,
    price: 620000,
    area: 2500,
    bedrooms: 0,
    bathrooms: 0,
    parkingSpots: 0,
    city: 'Cotia',
    neighborhood: 'Jardim Pinheirinho',
    address: 'Estrada Municipal, Km 12',
    state: 'SP',
    zipCode: '06708-000',
    images: [
      {
        id: 'p4-1',
        url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
        alt: 'Vista aérea do terreno',
        isPrimary: true,
      },
    ],
    featured: false,
    createdAt: '2024-05-04T11:20:00Z',
    updatedAt: '2024-05-04T11:20:00Z',
    brokerId: 'broker-3',
    brokerName: 'Pedro Costa',
    brokerPhone: '(11) 95555-4444',
  },
]

export const allProperties: Property[] = [...mockProperties, ...pendingProperties]

export const featuredProperties = mockProperties.filter((p) => p.featured)
